### ISSUE TITLE
Create request-for-storage dialog

### ISSUE THREAD

**Issue by benbierens** [codex-storage/codex-frontend#14]
Similar changes are needed for this dialog.

- Explain that duration is in seconds.
- Proof-probability should be an editable dropdown of predefined values:
1 (low durability guarantee)
3 (medium durability guarantee)
6 (strong durability guarantee)
User should be able to enter any whole number > 0 and < 999
- Missing expiry field, should be editable dropdown of predefined values:
5 minutes (small datasets)
15 minutes (medium datasets)
1 hour (large datasets)
User should be able to enter any duration >= 1 minute and <= 1 day
- Change Download button to "Create" to match dialog name

Bonus:
- As a user, I don't want to type seconds in the duration and expiry fields. Give me a nice UI control that lets me easily select a number of minutes, hours, and days.

**Comment by Shorssaud** [comment]
still left to do:
- [x] editable dropdown for expiry field
- [x] make duration and expiry window close when clicking outside of it
