### ISSUE TITLE
Codex endpoint URL from docker environment variable

### ISSUE THREAD

**Issue by benbierens** [codex-storage/codex-frontend#2]
The URL of the Codex node to connect to should be settable from a docker environment variable. 
Something like this:
<img width="273" alt="image" src="https://github.com/codex-storage/codex-frontend/assets/39762930/46ab8afe-c388-49ae-a3e0-b8e3104d2191">
(Maybe if the URL is set, we can have the app default to the Data page instead of setting?)

**Comment by Shorssaud** [comment]
I just pushed so you can modify the REACT_APP_CODEX_URL value in the /frontend/.env file

**Comment by Shorssaud** [comment]
Fixed with the Refactor nginx, the environment variable is set from the docker compose file
